# Generated by Django 3.1.7 on 2021-03-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nmUsuario', max_length=80, verbose_name='Usuario')),
                ('email', models.EmailField(db_column='nmEmail', max_length=50, unique=True, verbose_name='email')),
                ('password', models.CharField(db_column='nmSenha', max_length=100, verbose_name='senha')),
                ('profile', models.PositiveSmallIntegerField(db_column='nuProfile', verbose_name='perfil')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'ecdtUsuario',
            },
        ),
    ]
