# Generated by Django 3.1.7 on 2021-03-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210309_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Junior'), (2, 'Pleno'), (3, 'Sênior')], db_column='nuProfile', verbose_name='perfil'),
        ),
    ]
