# Generated by Django 3.1.7 on 2021-03-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210309_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(db_column='nmSenha', max_length=30, verbose_name='senha'),
        ),
    ]
