# Generated by Django 3.1.7 on 2021-03-09 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(db_column='idProjeto', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='cdProjeto', max_length=20, verbose_name='codigo')),
                ('name', models.CharField(db_column='nmProjeto', max_length=80, verbose_name='nome')),
                ('description', models.TextField(db_column='deProjeto', null=True, verbose_name='descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('approval_date', models.DateTimeField(db_column='dtAprovacao', null=True, verbose_name='data aprovação')),
                ('cancellation_date', models.DateTimeField(db_column='dtCancelamento', null=True, verbose_name='data cancelamento')),
                ('status', models.PositiveSmallIntegerField(db_column='flStatus', verbose_name='status')),
                ('user', models.ForeignKey(db_column='nuUsuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'db_table': 'eptfProjeto',
            },
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(db_column='idGerenciamento', primary_key=True, serialize=False)),
                ('budget', models.DecimalField(db_column='vlOrcamento', decimal_places=2, max_digits=9, verbose_name='orçamento')),
                ('spent', models.DecimalField(db_column='vlGasto', decimal_places=2, max_digits=9, verbose_name='Gasto')),
                ('project', models.ForeignKey(db_column='nuProjeto', on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='projeto')),
            ],
            options={
                'verbose_name': 'Gerenciamento',
                'verbose_name_plural': 'Gerenciamentos',
                'db_table': 'egstGerenciamento',
            },
        ),
    ]
